site_name: K8s DataModel
site_description: A CLI tool to model and analyze Kubernetes cluster data including CRDs, operators, and OLM components
site_author: brunseba
site_url: https://brunseba.github.io/k8s-datamodel/

repo_name: brunseba/k8s-datamodel
repo_url: https://github.com/brunseba/k8s-datamodel
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Project Overview: PROJECT_SUMMARY.md
  - Features:
    - CRD Export Examples: CRD_EXPORT_EXAMPLES.md
    - OLM Integration: OLM_FEATURE_SUMMARY.md
  - Usage:
    - Quick Start: usage/quick-start.md
    - CRDs: usage/crds.md
    - Operators: usage/operators.md
    - Cluster Operations: usage/cluster.md
    - Database Operations: usage/database.md
    - Output Formats: usage/output-formats.md
  - Examples:
    - Overview: examples.md
    - Database Workflows: examples/database-workflows.md
    - OLM Management: examples/olm-workflows.md
    - Security & Compliance: examples/security-compliance.md
  - API Reference:
    - CLI Commands: api/cli.md
    - Core Modules: api/core.md
  - Contributing: contributing.md
  - Release Notes: RELEASE_NOTES.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: brunseba/k8s-datamodel
      branch: main
  - mermaid2:
      arguments:
        theme: auto
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brun-s
  version:
    provider: mike
    default: 0.4.0

extra_css:
  - stylesheets/extra.css

watch:
  - src/
  - README.md
